### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by JiewenKuang** [AndresCasado/pergamo#1]
When I try to download the data, I am prompted with this problem, making it impossible to log in
![1665995765660](https://user-images.githubusercontent.com/113975852/196130246-e9e3941a-799f-42a4-9f3e-fc0bf406d2ef.jpg)

**Comment by AndresCasado** [comment]
Hello,

The link was not correct and was set only for members of our organization. The current link is set to public, can you please try again?

**Comment by JiewenKuang** [comment]
In the README.md file I see two types of data, they are **DatosBuff** and **DatosDan**. 
![1666008528488](https://user-images.githubusercontent.com/113975852/196173473-fdaf3542-2048-4034-87e2-660751fed0db.jpg)


But when I open the dataset link, there is only **DatosDan** dataset in the web page.
![1666008826198](https://user-images.githubusercontent.com/113975852/196174314-06d0b4de-9ee9-434b-a594-6eedd058dbf5.jpg)

**Comment by AndresCasado** [comment]
Sorry, we noticed publishing the BUFF dataset could be against their license, so we removed it. If we find it possible we will reupload it again.
