### ISSUE TITLE
The program has no errors, but it does not produce any results.

### ISSUE THREAD

**Issue by Liu-xiaoyu11** [AndresCasado/pergamo#12]
Hello @AndresCasado ：
I am trying to recreate the results using DatosDanCompressed.zip.
However, when I run the "run_recons.sh" file, it executes successfully but yields no results. I suspect that there might be an error with my path settings. Despite repeatedly modifying it, I still cannot get any results. I am very much looking forward to your reply.
<img width="530" alt="77b50c44010ea24e752de3a25979c78" src="https://github.com/AndresCasado/pergamo/assets/165904272/4d8db43a-75ec-483a-b86b-88e3edc49aa7">
<img width="528" alt="d446a3ffdfc3257e0614d52710385e5" src="https://github.com/AndresCasado/pergamo/assets/165904272/6c457a7f-58f8-4303-895d-21a0eb8a8ca5">
I am replicating the code in a Windows environment and have installed Git for Windows.I am very much looking forward to your reply.

**Comment by AndresCasado** [comment]
From your screenshots it looks like you're using Windows. I don't use Windows for developing so I can't be sure, but it looks like MinGW expects the path to be `/e/pergamo-master/DatosDan/sequences`

Could you try that?

**Comment by Liu-xiaoyu11** [comment]
@AndresCasado 
I'm very sorry for the trouble. I am indeed using the Windows system, and I have tried the above path but still no results.

**Comment by Liu-xiaoyu11** [comment]
Thank you.The current project directory is as follows, thank you very much for your reply.
<img width="236" alt="befef2487ce41e626b57ec8e190dcae" src="https://github.com/AndresCasado/pergamo/assets/165904272/46df6ee3-37a8-46d1-a950-9e9f5d69e017">
<img width="265" alt="87ad90efa61cbdd89e8120673096bcc" src="https://github.com/AndresCasado/pergamo/assets/165904272/880b2f9f-350d-4dd2-ae10-8cce6296f99c">
I am very eager to learn from your article, so I really want to replicate it.

> From your screenshots it looks like you're using Windows. I don't use Windows for developing so I can't be sure, but it looks like MinGW expects the path to be `/e/pergamo-master/DatosDan/sequences`
> 
> Could you try that?

**Comment by AndresCasado** [comment]
Sadly, I don't have a Windows environment to test, but let's try to see how Python works in your setup.

Please, put the following command in a new .sh file and run the .sh file

`python3 - c 'import os; print(os.getcwd())'`

**Comment by Liu-xiaoyu11** [comment]
> Sadly, I don't have a Windows environment to test, but let's try to see how Python works in your setup.
> 
> Please, put the following command in a new .sh file and run the .sh file
> 
> `python3 - c 'import os; print(os.getcwd())'`

@AndresCasado  Just now, I tried to print my current working directory but found that there was no output. It might be that my configuration in the Windows environment is incorrect. I'll modify it now, and if it works out, I'll share the good news with you. Thank you very much for your reply; I might come back later to leave a message. Once again, I express my gratitude to you.

**Comment by AndresCasado** [comment]
Reopen this issue or open another one if you find a problem related to the project.

Best regards, I hope you get it working! 👍
