### ISSUE TITLE
Visualized result only shows the clothes, not the body model. It should be the body model wearing the clothes, right?

### ISSUE THREAD

**Issue by Liu-xiaoyu11** [AndresCasado/pergamo#14]
Hello,  @AndresCasado 
The method you guided me through in Blender didn't combine the clothes with the body model. What exactly is the role of _body.pc2? Currently, my visualization result only shows the clothes. I'm a bit lost on how to solve this issue, so I'd like to ask for your advice. Also, regarding the animation effect of the clothes, are they supposed to be colorless?
![image](https://github.com/AndresCasado/pergamo/assets/165904272/f08bbd9a-1b8e-4597-a158-12014ee55171)
Looking forward to your response.

**Comment by AndresCasado** [comment]
The garment and the body meshes are different and are not combined at any point. The `*_body.pc2` files are to be applied to a SMPL-X mesh.

PERGAMO doesn't apply color or textures. You can set it to whatever material you want for rendering in Blender.

While I'm happy to help you set up PERGAMO, please understand that I don't have the time available to guide you on using Blender or other questions not directly about PERGAMO.

**Comment by Liu-xiaoyu11** [comment]
I 'm very sorry, this question I asked the partial problem, give you trouble.
