### ISSUE TITLE
Which AMASS_.npz should be placed into the test_sequence folder?

### ISSUE THREAD

**Issue by Liu-xiaoyu11** [AndresCasado/pergamo#16]
Hi, @AndresCasado 
Which AMASS_.npz should be placed into the test_sequence folder?
![image](https://github.com/AndresCasado/pergamo/assets/165904272/7d4d2e77-f944-4ac9-9abe-38ad68370414)
Looking forward to your response.

**Comment by AndresCasado** [comment]
All AMASS datasets are supposed to have the same format. We used CMU. You can download them here: https://amass.is.tue.mpg.de/

**Comment by Liu-xiaoyu11** [comment]
I understand, I now go to this website download, thank you very much for your guidance.
