### ISSUE TITLE
How to convert SMPL-X to SMPL?

### ISSUE THREAD

**Issue by Liu-xiaoyu11** [AndresCasado/pergamo#17]
Hello, @AndresCasado ：
I apologize for bothering you again. I wanted to ask about the method you used for converting the results from EXPOSE, which are in SMPL-X format, to SMPL format. The readme mentions that the output of EXPOSE is SMPL-X. I've tried several methods for this conversion, but the results haven't been accurate.
<img width="484" alt="f42b39a939f90688b78f01c6d9354d9" src="https://github.com/AndresCasado/pergamo/assets/165904272/0e719813-aa26-44f6-8333-5accccf4da3f">
I greatly appreciate it if you could take the time to review my message. I'm looking forward to hearing back from you soon.

**Comment by AndresCasado** [comment]
Hi again!

The conversion between different SMPL models is available in the official repository for SMPL-X, more specifically in the `transfer_model` folder. You can find the instructions here https://github.com/vchoutas/smplx/tree/main/transfer_model

Hope your work is progressing well!
