### ISSUE TITLE
Some problems about `Running the project`

### ISSUE THREAD

**Issue by yyyqwq** [AndresCasado/pergamo#3]
Sorry I am newbie.

I have finished Install instructions. But I have some problems about `Running the project`  now.
I want to input my own video to drive the SMPL model. It seems that we need to convert the video(mp4) to amass scripts(motion sequences)， but I don't find the mothods or third-party(like alphapose) to do the thing. I find that there are many sequences in dataset, so Could you tell me how to convert the video(mp4) to the certain motion sequences in this project?

Thank you!

**Comment by dancasas** [comment]
As we explain in the end of Section 4.1 of the paper, we estimate the SMPL pose of the subject in the input video using the method [ExPose](https://github.com/vchoutas/expose) by Choutas _et al_. 

Hence, if you wish to run PERGAMO with your own videos, you first have to pass it through ExPose to obtain SMPL parameters, but you will also need to estimate segmentation masks and per-pixel normals. It is all explain in Section 4.1.
