### ISSUE TITLE
how to use events.out.tfevents.xxxxx?

### ISSUE THREAD

**Issue by yyyqwq** [AndresCasado/pergamo#6]
I have downloaded DataDanBrown and ran the reconstruction_scipy.py. Then I got many events.out.tf.events.xxxxx.xxxx.xxx. Soory, But I don't know how to use it.

**Comment by AndresCasado** [comment]
Those are Tensorboard logs, this tutorial may help https://www.tensorflow.org/tensorboard/get_started?hl=en
