### ISSUE TITLE
test

### ISSUE THREAD

**Issue by nagexiaochengzi** [AndresCasado/pergamo#7]
Which test did you use for the amass dataset, or is this-project predictable for all of amass?

**Comment by AndresCasado** [comment]
We used the CMU dataset. You can predict for any SMPL pose, but poses too far from our training set will be problematic.

**Comment by dancasas** [comment]
Hi @nagexiaochengzi, we use the AMASS sequences that are specified in Figure 7 of our paper. But our project should be compatible with any SMPL pose, although the quality of the results might vary depending on how different from the training set your test poses are.

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/2377307/223382200-63b952f9-8502-45f2-b65c-e53d3555bb16.png">

**Comment by nagexiaochengzi** [comment]
Your zip file is corrupted

**Comment by AndresCasado** [comment]
Can you specify which one? I just tried downloading and unzipping `DatosDanCompressed.zip` and it works

**Comment by nagexiaochengzi** [comment]
The downloaded dataset cannot be unpacked
<img width="660" alt="屏幕截图 2023-03-08 200650" src="https://user-images.githubusercontent.com/50610836/223709470-fa919793-0fd1-4d25-8f98-581670b3f2e5.png">

**Comment by nagexiaochengzi** [comment]
<img width="500" alt="屏幕截图 2023-03-08 200650" src="https://user-images.githubusercontent.com/50610836/223709884-d7fb5e97-004a-48e9-88ba-048d21c7436d.png">

**Comment by AndresCasado** [comment]
OneDrive usually fails at compressing multiple selected files. Try to download them one by one.

**Comment by nagexiaochengzi** [comment]
thanks
