### ISSUE TITLE
other paper

### ISSUE THREAD

**Issue by nagexiaochengzi** [AndresCasado/pergamo#9]
Do you have the source code for the article "ULNeF: Untangled Layered Neural Fields for Mix-and-Match Virtual Try-On", I'm more interested in running it.

**Comment by dancasas** [comment]
We haven't released that one, sorry.

**Comment by nagexiaochengzi** [comment]
Thank you, when is it expected to be released?

**Comment by dancasas** [comment]
We don't have any timeline for ULNeF release.

**Comment by nagexiaochengzi** [comment]
thanks
